# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Azath < Formula
  desc "🏰 Azath - Protect your secrets from leaking into git"
  homepage "https://azath.sh"
  version "0.4.0"
  license "MIT"

  depends_on "git" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/azathsh/azath/releases/download/v0.4.0/azath_0.4.0_darwin_amd64.tar.gz"
      sha256 "3f8b30d0a502e98275d66bf6355d4dafde2a0df2ff92cc49ba2e067546d01a05"

      define_method(:install) do
        bin.install "azath"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/azathsh/azath/releases/download/v0.4.0/azath_0.4.0_darwin_arm64.tar.gz"
      sha256 "0d0c41e8c0da5fdf038e4c90055915dff0e05c2213ceafc53260b2a19b1939a8"

      define_method(:install) do
        bin.install "azath"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/azathsh/azath/releases/download/v0.4.0/azath_0.4.0_linux_amd64.tar.gz"
      sha256 "c09afa8c347846ea49a07692cb1d7d378f6322528af1e039f6e466cb3e226f5f"
      define_method(:install) do
        bin.install "azath"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/azathsh/azath/releases/download/v0.4.0/azath_0.4.0_linux_arm64.tar.gz"
      sha256 "f4bf17cef69daf21830ed8f8d081adeece4ad42a6e389122db6341e274e0bca4"
      define_method(:install) do
        bin.install "azath"
      end
    end
  end

  conflicts_with "azath-bin"

  def caveats
    <<~EOS
      🏰 Azath has been installed!

      To get started:
        azath init          # Install git hooks in your repo
        azath scan-all .    # Scan for existing secrets

      For more information: https://azath.sh/docs
    EOS
  end

  test do
    system "#{bin}/azath", "version"
  end
end
