# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Azath < Formula
  desc "🏰 Azath - Protect your secrets from leaking into git"
  homepage "https://azath.sh"
  version "0.4.4"
  license "MIT"

  depends_on "git" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/azathsh/azath/releases/download/v0.4.4/azath_0.4.4_darwin_amd64.tar.gz"
      sha256 "8d23cc2f2f8104a351a3dcb034ba43baf57d07c4af981f39f26aee9af9751892"

      define_method(:install) do
        bin.install "azath"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/azathsh/azath/releases/download/v0.4.4/azath_0.4.4_darwin_arm64.tar.gz"
      sha256 "fc865fa468610d05ae32ede53763972fc08f9fdfabb9aa4421c698182a6b28c5"

      define_method(:install) do
        bin.install "azath"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/azathsh/azath/releases/download/v0.4.4/azath_0.4.4_linux_amd64.tar.gz"
      sha256 "5e6bfc55ecf8530e96e6333102325ccfffd7bea6a04c95404d46c53ceb135965"
      define_method(:install) do
        bin.install "azath"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/azathsh/azath/releases/download/v0.4.4/azath_0.4.4_linux_arm64.tar.gz"
      sha256 "e173af78f625dcdd067731d1ae4d1a87c7ac66b9e6ee4312fc982758978086f6"
      define_method(:install) do
        bin.install "azath"
      end
    end
  end

  conflicts_with "azath-bin"

  def caveats
    <<~EOS
      🏰 Azath has been installed!

      To get started:
        azath init          # Install git hooks in your repo
        azath scan-all .    # Scan for existing secrets

      For more information: https://azath.sh/docs
    EOS
  end

  test do
    system "#{bin}/azath", "version"
  end
end
